### PR TITLE
Fixed coffee data

### LINKED ISSUE #30: Fix coffee data
`preparation` data in the coffee object is not correct, let's get it fixed, also make sure that everything else is correct.

### PR DESCRIPTION
**Pull request by DEJENERUTA**
Fixes #30

### CODE REVIEW

**Review by bence-toth — CHANGES_REQUESTED** [review]
I can see an empty file called `coffeeObjects.js`, can you please remove that?

File: src/coffee.js [hunk 1]
```diff
@@ -14,17 +14,19 @@ const coffee = [
   {
     name: "Aynu",
     profile: "clean",
-    acidity: "round",
+    characteristic: "round",
```
Comment (bence-toth) [inline src/coffee.js:17]: Don't name these keys back please. Keys must be called `acidity` for this (clean, round, or acidic), `characteristics` for taste/tasing profile, and `roastLevels` for roast levels (instead of roast profile). Values for `roastLevels` must be `"dark"` etc. instead of `"dark roast"` etc. Please don't change these things.

File: src/coffee.js [hunk 2]
```diff
@@ -14,17 +14,19 @@ const coffee = [
...
     url: "https://impactroasters.dk/pages/about-coffe-coffee-guide",
```
Comment (bence-toth) [inline src/coffee.js:18]: Let's fix the URLs

File: src/coffee.js [hunk 3]
```diff
@@ -48,19 +50,14 @@ const coffee = [
   {
     name: "Beza",
     profile: "rich",
-    acidity: "sweet",
+    characteristic: "sweet",
     url: "https://impactroasters.dk/pages/about-coffe-coffee-guide",
     image: BezaImage,
-    characteristics: ["intense sweetness", "spicy", "forest berry aroma"],
+    taste: ["chocolate", "spicy", "floral"],
+    tastingProfile: ["intense sweetness", "spicy", "forest berry aroma"],
```
Comment (bence-toth) [inline src/coffee.js:57]: Let's not reintroduce taste/tasting profile please. We only keep one, which is called `characteristics`.

**Review by bence-toth — CHANGES_REQUESTED** [review]
Added some comments. Please don't change the structure of the JSON, only the values.

File: src/useSteps.js [hunk 4]
```diff
@@ -18,8 +18,8 @@ const options = [
   { type: "characteristic", value: "spicy", label: "Spicy" },
   {
     type: "characteristic",
-    value: "forest berry aroma",
-    label: "Forest berry aroma",
+    value: "forest berry",
+    label: "forest berry",
```
Comment (bence-toth) [inline src/useSteps.js:22]: Make sure that labels are all capitalised:
```suggestion
    label: "Forest berry",
```

Also there should be no repetitions here, and no unused characteristics.

File: src/coffee.js [hunk 5]
```diff
@@ -51,16 +52,10 @@ const coffee = [
...
     processing: ["sundried"],
     roastLevels: ["dark", "light"],
-    preparation: [
-      "espresso",
-      "cafe latte",
-      "cappuccino",
-      "cortado",
-      "flat white",
-    ],
+    preparation: ["aeropress", "chemex and hario v60"],
```
Comment (bence-toth) [inline src/coffee.js:58]: Let's capitalise these for all coffee:
```suggestion
    preparation: ["Aeropress", "Chemex and Hario v60"],
```

File: src/coffee.js [hunk 6]
```diff
@@ -17,14 +17,15 @@ const coffee = [
     acidity: "round",
     url: "https://impactroasters.dk/pages/about-coffe-coffee-guide",
     image: AynuImage,
-    characteristics: ["fruit acidity", "nut aroma"],
+    characteristics: ["rounded", "fruit acidity", "nut aroma"],
```
Comment (bence-toth) [inline src/coffee.js:20]: For the `characteristics` in general, this should be done:

Let's merge `citrus aroma` and `fresh citrus`, keep only `citrus`

Let's merge `fruit acidity` and `fruity`, keep only `fruity`

Let's get rid of `sweet` (it's also in acidity)

Let's get rid of `slightly acidic` (it's also in acidity)

Let's simplify these characteristic names:
- `nut aroma` -> `nut`
- `forest berry aroma` -> `forest berry`
- `nougat aroma` -> `nougat`
- `chocolate aroma` -> `chocolate`

So at the end of the day, the list of characteristics should looks something like this:
- `chocolate`
- `citrus`
- `delicate sweetness`
- `floral`
- `forest berry`
- `fruity`
- `honey`
- `intense sweetness`
- `nougat`
- `nut`
- `spicy`

**Review by bence-toth — CHANGES_REQUESTED** [review]
Added some comments

**Comment by bence-toth** [comment]
There is an empty file called `src/assets/coffeeObjects.js` in this PR, please delete it

File: src/coffee.js [hunk 7]
```diff
@@ -15,17 +15,18 @@ const coffee = [
     name: "Aynu",
     profile: "clean",
     acidity: "round",
-    url: "https://impactroasters.dk/pages/about-coffe-coffee-guide",
+    url: "https://impactroasters.dk/products/aynu-limu",
     image: AynuImage,
-    characteristics: ["fruit acidity", "nut aroma"],
+    characteristics: ["rounded", "fruity", "nut"],
```
Comment (bence-toth) [inline src/coffee.js]: Let's remove `rounded` from here.

File: src/coffee.js [hunk 8]
```diff
@@ -15,17 +15,18 @@ const coffee = [
...
-      "cafe latte",
-      "cappuccino",
-      "cortado",
-      "flat white",
+      "Espresso",
+      "Americano",
+      "French Press",
+      "Filter Drip",
+      "Mokapot",
+      "Flat White",
```
Comment (bence-toth) [inline src/coffee.js]:
```suggestion
      "French press",
      "Filter drip",
      "Mokapot",
      "Flat white",
```

File: src/coffee.js [hunk 9]
```diff
@@ -83,17 +78,17 @@ const coffee = [
...
-      "espresso",
-      "cafe latte",
-      "cappuccino",
-      "cortado",
-      "flat white",
+      "Espresso",
+      "Cafe Latte",
+      "Cappuccino",
+      "Cortado",
+      "Flat White",
```
Comment (bence-toth) [inline src/coffee.js]:
```suggestion
      "Espresso",
      "Cafe latte",
      "Cappuccino",
      "Cortado",
      "Flat white",
```

File: src/coffee.js [hunk 10]
```diff
@@ -117,22 +112,12 @@ const coffee = [
...
     acidity: "round",
-    url: "https://impactroasters.dk/pages/about-coffe-coffee-guide",
+    url: "https://impactroasters.dk/products/coffee-beans-kaffa-forest",
     image: KaffaImage,
-    characteristics: [
-      "forest berry aroma",
-      "delicate sweetness",
-      "chocolate aroma",
-    ],
+    characteristics: ["forest berry", "delicate sweetness", "chocolate "],
```
Comment (bence-toth) [inline src/coffee.js]:
```suggestion
    characteristics: ["forest berry", "delicate sweetness", "chocolate"],
```

File: src/coffee.js [hunk 11]
```diff
@@ -117,22 +112,12 @@ const coffee = [
...
     processing: ["sundried"],
     roastLevels: ["dark", "medium", "light"],
-    preparation: [
-      "espresso",
-      "cafe latte",
-      "cappuccino",
-      "cortado",
-      "flat white",
-    ],
+    preparation: ["Filter Drip", "Chemex and Hario v60"],
```
Comment (bence-toth) [inline src/coffee.js]:
```suggestion
    preparation: ["Filter drip", "Chemex and Hario v60"],
```

File: src/coffee.js [hunk 12]
```diff
@@ -155,18 +140,12 @@ const coffee = [
...
     processing: ["washed"],
     roastLevels: ["dark", "medium", "light"],
-    preparation: [
-      "espresso",
-      "cafe latte",
-      "cappuccino",
-      "cortado",
-      "flat white",
-    ],
+    preparation: ["Filter Drip", "French Press"],
```
Comment (bence-toth) [inline src/coffee.js]:
```suggestion
    preparation: ["Filter drip", "French press"],
```

File: src/coffee.js [hunk 13]
```diff
@@ -189,18 +168,12 @@ const coffee = [
...
     processing: ["sundried"],
     roastLevels: ["dark", "medium", "light"],
-    preparation: [
-      "espresso",
-      "cafe latte",
-      "cappuccino",
-      "cortado",
-      "flat white",
-    ],
+    preparation: ["Filer Drip", "French Press"],
```
Comment (bence-toth) [inline src/coffee.js]:
```suggestion
    preparation: ["Filer drip", "French press"],
```

**Review by bence-toth — APPROVED** [review]
